apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
          app: busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox # This label identifies our application, used for filtering output
    spec:
      # securityContext: # Best practice for security - if possible never run as root (which is default)
      # runAsNonRoot: true
      restartPolicy: Always
      containers:
        - name: busybox
          image: k8s.gcr.io/busybox
          # command: ["/bin/sh", "-c", "cp /standalone/configmap/* /standalone/config"]
          command: ["/bin/sh", "-c", "--"]
          args: ["while true; do sleep 30; done ;"]
